# Generated by Django 4.0 on 2022-01-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_address', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_city', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_state', models.CharField(blank=True, max_length=5, null=True)),
                ('cust_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('cust_country', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_num', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productnotes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.CharField(max_length=10)),
                ('note_date', models.DateTimeField()),
                ('note_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productnotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prod_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vend_id', models.AutoField(primary_key=True, serialize=False)),
                ('vend_name', models.CharField(max_length=50)),
                ('vend_address', models.CharField(blank=True, max_length=50, null=True)),
                ('vend_city', models.CharField(blank=True, max_length=50, null=True)),
                ('vend_state', models.CharField(blank=True, max_length=5, null=True)),
                ('vend_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('vend_country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'vendors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('order_num', models.OneToOneField(db_column='order_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='toy.orders')),
                ('order_item', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'orderitems',
                'managed': False,
            },
        ),
    ]
