# Generated by Django 4.0 on 2021-12-12 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '开发'), (1, '运维'), (2, '设计'), (3, '测试'), (4, '管理')], verbose_name='职位类别')),
                ('job_name', models.CharField(max_length=32, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '广州'), (3, '深圳'), (4, '西安'), (5, '成都'), (6, '杭州'), (7, '南京')], verbose_name='工作城市')),
                ('job_responsibility', models.TextField(max_length=1024, verbose_name='职位职责')),
                ('job_requirement', models.TextField(max_length=1024, verbose_name='职位要求')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='创建人')),
            ],
        ),
    ]
